version: '3.9'

services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - C:\project\learning\src:/var/www
      - C:\project\learning\nginx\nginx.conf:/etc/nginx/nginx.conf
      - C:\project\learning\nginx\ssl:/etc/nginx/ssl
    container_name: learning_server_nginx
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external:
      name: proxy
