<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHS85FTF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHS85FTF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHS85FTF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHS85FTF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHS85FTF\App_KernelDevDebugContainer([
    'container.build_hash' => 'HS85FTF',
    'container.build_id' => '71d74843',
    'container.build_time' => 1648480061,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHS85FTF');
